name: Check whether the workflow owner can use ARC runners

on:
  workflow_call:
    inputs:
      user_name:
        required: true
        type: string
        description: The name of the workflow owner.

    outputs:
      workflow-type:
        description: Type of runners to use
        value: ${{ jobs.check-user.outputs.workflow-type }}

jobs:
  check-user:
    runs-on: linux.4xlarge
    outputs:
      workflow-type: ${{ steps.set-condition.outputs.workflow-type }}
    steps:
      - name: Check if user is in arc_users.yml
        id: set-condition
        run: |
          REPO_OWNER="pytorch"
          REPO_NAME="test-infra"
          ISSUE_NUMBER="5132"

          COMMENTS=$(curl https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER/comments)
          USER_LIST=$(echo "$COMMENTS" | tr -d '\r\n' | jq '.[0].body' -r)

          if [[ ${USER_LIST:0:1} == "!" ]]; then
            echo "workflow-type=label" >> $GITHUB_OUTPUT
          elif [[ ${USER_LIST:0:1} == "*" ]]; then
            echo "workflow-type=rg" >> $GITHUB_OUTPUT
          elif echo "$USER_LIST" | grep -q "${{ inputs.user_name }}"; then
            echo "workflow-type=rg" >> $GITHUB_OUTPUT
          else
            echo "workflow-type=label" >> $GITHUB_OUTPUT
          fi
